[package]
name = "content"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
html-escape.workspace = true
