[[language]]
name = "rust"
[language-server.rust-analyzer.config.cargo]
features = ["all"] # each package has "all" feature for convenience
[language-server.rust-analyzer.environment]
CARGO_TARGET_DIR = "target/rust-analyzer"
