[[language]]
name = "rust"
formatter = { command = "leptosfmt", args = ["--stdin", "--rustfmt"] }
# [language-server.rust-analyzer.config]
# procMacro = { ignored = { leptos_macro = ["server"] } }
# [language-server.rust-analyzer.config.check]
# command = "clippy"
[language-server.rust-analyzer.config.cargo]
# features = "all"
features = ["all"] # each package has "all" feature for convenience
[language-server.rust-analyzer.environment]
CARGO_TARGET_DIR = "target/rust-analyzer"
