[package]
name = "cli"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bcrypt = { workspace = true }
clap = { version = "4.3", features = ["derive"] }
prisma_client = { workspace = true }
prisma-client-rust = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
