[package]
name = "lapa_admin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1"
axum = { workspace = true, optional = true }
js-sys = { workspace = true, optional = true }
chrono = { workspace = true }
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
cfg-if = { workspace = true }
leptos = { workspace = true }
leptos_axum = { workspace = true, optional = true }
leptos_meta = { workspace = true }
leptos_router = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde-wasm-bindgen = { workspace = true }
simple_logger = { workspace = true, optional = true }
tokio = { workspace = true }
tower = { workspace = true, optional = true }
tower-http = { workspace = true, optional = true }
tower_governor = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
thiserror = { workspace = true }
http = { workspace = true }
prisma_client = { workspace = true, optional = true }
prisma-client-rust = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }

async-trait = { version = "0.1", optional = true }
axum_session = { version = "0.3", default-features = false, optional = true }
axum_session_auth = { version = "0.3", default-features = false, optional = true }
bcrypt = { version = "0.15", optional = true }
image = { version = "0.24", optional = true, features = ["webp-encoder"] }
wasm-bindgen-futures = { version = "0.4" }
# cookie = "0.17.0"
kamadak-exif = { version = "0.5", optional = true }

[features]
prod = ["compression", "ratelimit"]
compression = ["tower-http?/compression-full"]
ratelimit = []
hydrate = [
    "dep:wasm-bindgen",
    "dep:web-sys",
    "dep:js-sys",
    "leptos/hydrate",
    "leptos_meta/hydrate",
    "leptos_router/hydrate",
]
ssr = [
    "dep:axum",
    "dep:axum_session",
    "dep:axum_session_auth",
    "dep:async-trait",
    "dep:bcrypt",
    "dep:kamadak-exif",
    "dep:image",
    "dep:leptos_axum",
    "dep:simple_logger",
    "dep:prisma_client",
    "dep:prisma-client-rust",
    "dep:tower",
    "dep:tower_governor",
    "dep:tower-http",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
]

[package.metadata.cargo-all-features]
denylist = ["axum", "tokio", "tower", "tower-http", "leptos_axum"]
skip_feature_sets = [["ssr", "hydrate"]]

[package.metadata.leptos]
# output-name = "lapa_admin"
site-root = "target/admin"
site-pkg-dir = "pkg"
style-file = "style/main.css"
assets-dir = "public"
site-addr = "127.0.0.1:4143"
reload-port = 4444
end2end-cmd = "npx playwright test"
end2end-dir = "end2end"
browserquery = "defaults"
watch = false
env = "DEV"
bin-features = ["ssr"]
bin-default-features = false
lib-features = ["hydrate"]
lib-default-features = false
